apiVersion: v2
name: image-replicator
description: A Kubernetes Validating Webhook to verify and replicate container images to target registries
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - kubernetes
  - webhook
  - validation
  - container
  - registry
maintainers:
  - name: "Svitio s.r.o."
home: https://github.com/svitio-company/image-replicator
sources:
  - https://github.com/svitio-company/image-replicator