{{- if .Values.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "image-replicator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "image-replicator.labels" . | nindent 4 }}
spec:
  secretName: {{ include "image-replicator.tlsSecretName" . }}
  duration: {{ .Values.certManager.certificate.duration }}
  renewBefore: {{ .Values.certManager.certificate.renewBefore }}
  issuerRef:
    kind: {{ .Values.certManager.issuer.kind }}
    name: {{ include "image-replicator.issuerName" . }}
  dnsNames:
    - {{ include "image-replicator.webhookServiceName" . }}
    - {{ include "image-replicator.webhookServiceName" . }}.{{ .Release.Namespace }}
    - {{ include "image-replicator.webhookServiceName" . }}.{{ .Release.Namespace }}.svc
    - {{ include "image-replicator.webhookServiceName" . }}.{{ .Release.Namespace }}.svc.cluster.local
    {{- with .Values.certManager.certificate.dnsNames }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
