{{- if and (not .Values.certManager.enabled) (not .Values.tls.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "image-replicator.tlsSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "image-replicator.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  {{- if .Values.tls.crt }}
  tls.crt: {{ .Values.tls.crt | b64enc }}
  {{- end }}
  {{- if .Values.tls.key }}
  tls.key: {{ .Values.tls.key | b64enc }}
  {{- end }}
  {{- if .Values.tls.ca }}
  ca.crt: {{ .Values.tls.ca | b64enc }}
  {{- end }}
{{- end }}
