apiVersion: v1
kind: Service
metadata:
  name: {{ include "image-replicator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "image-replicator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: https
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "image-replicator.selectorLabels" . | nindent 4 }}
